### ISSUE TITLE
Kit runtime-config addon dry-run displays wrong output

### ISSUE THREAD

**Issue by michaelmccaskill** [genesis-community/bosh-genesis-kit#109]
Brand new proto deployment created with kit 2.0.1, opting for features:
- bosh-dns-healthcheck
- netop-access

Running `genesis do <env> -- runtime-config -n` gives the same output for **BOSH DNS Runtime Config** and **Access Runtime Config**. I would expect them to be different.

I have manually redacted the certs/keys
```
ubuntu@ip-10-175-0-181:~/deployments/bosh-deployments$ genesis do cf-lab-ops.yml -- runtime-config -n

Verifying availability of vault 'impervious-coffer' (http://127.0.0.1:8201)...ok

Running runtime-config addon for cf-lab-ops

Gathering current Exodus metadata for cf-lab-ops...

BOSH DNS Runtime Config
-----------------------
addons:
- include:
    stemcell:
    - os: ubuntu-trusty
    - os: ubuntu-xenial
  jobs:
  - name: bosh-dns
    properties:
      api:
        client:
          tls:
            ca: |
              <redacted>
            certificate: |
              <redacted>
            private_key: |
              <redacted>
        server:
          tls:
            ca: |
              <redacted>
            certificate: |
              <redacted>
            private_key: |
              <redacted>
      cache:
        enabled: true
    release: bosh-dns
  name: bosh-dns
releases:
- name: bosh-dns
  sha1: ba1e42c045c76ff097939f28e5168439c583686d
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.24.0
  version: 1.24.0


Access Runtime Config
---------------------
addons:
- include:
    stemcell:
    - os: ubuntu-trusty
    - os: ubuntu-xenial
  jobs:
  - name: bosh-dns
    properties:
      api:
        client:
          tls:
            ca: |
              <redacted>
            certificate: |
              <redacted>
            private_key: |
              <redacted>
        server:
          tls:
            ca: |
              <redacted>
            certificate: |
              <redacted>
            private_key: |
              <redacted>
      cache:
        enabled: true
    release: bosh-dns
  name: bosh-dns
releases:
- name: bosh-dns
  sha1: ba1e42c045c76ff097939f28e5168439c583686d
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.24.0
  version: 1.24.0
```
