### ISSUE TITLE
Ops-access runtime os-conf conflict

### ISSUE THREAD

**Issue by michaelmccaskill** [genesis-community/bosh-genesis-kit#114]
* Genesis 2.7.26
* Kit 2.0.1

When using the runtime hook to generate `genesis.ops-access`, it produces:
```
---  
addons:  
- jobs:  
    - exclude:  
        jobs:  
        - name: user_add  
        release: os-conf  
    name: user_add  
    properties:  
        persistent_homes: true  
        users:  
        - name: netop  
        public_key: 'ssh-rsa <REDACTED>'  
    release: os-conf  
    name: genesis-local-users  
releases:  
- name: os-conf  
    sha1: 42b1295896c1fbcd36b55bfdedfe86782b2c9fba  
    url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=20  
    version: '20'  
```
However, the deployment also wants to include os-conf 22.1.0, which results in:
```
Task 63 | 22:50:55 | Error: Runtime manifest specifies release 'os-conf' with version as '20'. This conflicts with version '22.1.0' specified in the deployment manifest.
```
