### ISSUE TITLE
Add a `sysop` User

### ISSUE THREAD

**Issue by jhunt** [genesis-community/bosh-genesis-kit#23]
Randomizing the password for the vcap account (via safe) is a good idea.

Making it super long is mean to operators who need to log in via vCenter's console, which does **NOT** allow you to copy / paste.

**Comment by jhunt** [comment]
Rather than abuse vcap, let's add a second user (there are ops files in BOSH-land to do this) which has the same rights as vcap, but also includes:

- Password authentication via the "physical" console
- Key-based authentication via SSH

Then, have the kit generate both password and key, allowing them to be set or overridden via params.

Something like:

```
params:
  sysops_password: super-sekrit
  sysops_ssh_key: |
    ssh-rsa AAAA..... joe@big.co
```
