### ISSUE TITLE
AWS default zone is `concat params.aws_region "a"`, it errors when the zone used is not region-a

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/bosh-genesis-kit#45]
In the kit, we have the following setting
```
meta:
  default:
    azs:
      - (( replace ))
      - (( concat params.aws_region "a" ))
```
When the bosh is not deployed in the default zone, you found out later when you go to deploy
```
Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'ami-03282638808c003e2 light':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"can't use multiple availability zones: subnet in us-east-1b, VM in us-east-1a","ok_to_retry":fa
lse}

Exit code 1
```
it will be nice to ask which zone are you deploying bosh to
